### ISSUE TITLE
Fix logger config to import logging format

### ISSUE THREAD

**Issue by ytturi** [gdalmau/WTFAU_bot#5]

**Comment by alirezamdv** [comment]
Hi, may i work on this ?!

**Comment by gdalmau** [comment]
@alirezamdv Sure 😄 

We commented the following line because we couldn't retrieve the `format` from the config parser. 

https://github.com/gdalmau/WTFAU_bot/blob/d730ada92ec8a804ff84ee20e1632c5a46a13f53/WTFAU_bot/confs.py#L45

**Comment by alirezamdv** [comment]
@gdalmau  hi,
I checked and everything works very well. Could you please take a look ?!
